# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. 
# Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” 
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. 
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:
# Welcome to the Cows and Bulls Game! 
# Enter a number: 
# >>> 1234
# 2 cows, 0 bulls
# >>> 1256
# 1 cow, 1 bull
# ...
# Until the user guesses the number.
import random

answer = str(random.randint(1234,9999))
guesses = 0

while True:
	guess = input('Enter a 4-digit number: ')
	cows = 0
	bulls = 0

	if guess == answer:
		print("YOU GOT IT!! " + answer + ". in " + str(guesses) + " tries!")
		break

	for x in range(3):
		if guess[x] == answer[x]:
			cows += 1
		elif guess[x] in answer:
			bulls += 1

	print(str(cows) + " Cows, " + str(bulls) + " Bulls.")